### ISSUE TITLE
Add support CEC remote via HDMI

### ISSUE THREAD

**Issue by vvd214** [EmbER-Dev/EmbER#13]
Can you please add support CEC remote via HDMI for this post

**Comment by vvd214** [comment]
Can you please add support CEC remote via HDMI. My board is G02REF running well with 1.01 realese version. One thing not work is CEC. when I run command "cec-client" via ssh. It show:
[root@MX ~]# cec-client
No device type given. Using 'recording device'
CEC Parser created - libCEC version 2.1.1
no serial port given. trying autodetect: FAILED

. Please fix for control xbmc via CEC like raspberry did. Thank you

**Comment by Stane1983** [comment]
Just a quick note, it's not easy as you think. And for sure you can't compare different platforms (eg amlogic and raspberry pi) because of different driver structure, hdmi implementation... g02ref is very first MX reference board from amlogic which was soon replaced with g18ref and it's no longer supported. So basically, if you have PCB which is designed against g02ref reference board you most likely will face some limitations or incompatibilities or not working stuff (like CEC for example). I think CEC is not working on g18ref too, but fixing it takes time and it doesn't give any guarantee that same solution will work on g02ref based board.
