### ISSUE TITLE
kernel sources

### ISSUE THREAD

**Issue by xlazom00** [EmbER-Dev/EmbER#6]
Any plans to release kernel source codes with modifications for specific hw?
I want to run full distro and boot over nfs on device but my latest kernel don't work really good :( 
And yours looks much much more stable

**Comment by dhead666** [comment]
Out of interest what issues you encountered ?

I have Arch running on my g18ref device but without ethernet and the system sending IPI to the CPUs, I'm not sure what is happening, need to figure out how to debug this.

See http://archlinuxarm.org/forum/viewtopic.php?f=27&t=7221

**Comment by xlazom00** [comment]
And I want fully working debian  :)
croniccorey has working kernel with all patches from amlogic and community
- devices integration

**Comment by dhead666** [comment]
You're a bit vague, what do you mean by "device integration" ?

From what I gather, ATM the Linux images supplied by Corey based on the https://github.com/CoreTech-Development/mx-common 

What I do miss are kernel defconfigs (and maybe board files) for anything else than the g18ref, as the Buildroot tree includes pre-compiled kernels it isn't clear what defconfigs are used or missing.

Again you aren't sharing what issues you encountered with, so stating "my latest kernel don't work really good" is pretty much empty claim as you can use exactly the same sources as Corey but compile against a recent gcc version and glibc and get unstable kernel, this is my situation as far as my limited understanding in Linux development goes.

**Comment by C-Prime90** [comment]
@dhead666 - The pre-built images supplied by me are built from source based on Amlogic's private repos (Obtained via. NDA/SLA), On my github i have public kernel with the changes up untill i switched over to Amlogic's private source, Also there is a 3.0.50 repo containing GPL release from Amlogic (2014/04/13).

@xlazom00 - I cannot release my kernel source publicly because i am under a NDA/SLA with Amlogic, the public source is usable with light modifications..
